# Colors (One Dark)
[colors]
  # Default colors
  [colors.primary]
  background = "#292D3E"
  foreground = "#abb2bf"

  # Normal colors
  [colors.normal]
  black = "#1e2127"
  red = "#e06c75"
  green = "#98c379"
  yellow = "#d19a66"
  blue = "#61afef"
  magenta = "#c678dd"
  cyan = "#56b6c2"
  white = "#abb2bf"

  # Bright colors
  [colors.bright]
  black = "#5c6370"
  red = "#e06c75"
  green = "#98c379"
  yellow = "#d19a66"
  blue = "#61afef"
  magenta = "#c678dd"
  cyan = "#56b6c2"
  white = "#ffffff"

  [colors.selection]
  background = "#7c6f64"
  text = "#ffffff"


[window]
opacity = 0.95

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 9.0

[cursor]
style = { shape = "Block", blinking = "Always" }



[shell]
program = "/bin/zsh"

