# Colors (One Dark)
[colors]
transparent_background_colors = true
  # Default colors
  [colors.primary]
  background = "#24283b"
  foreground = "#c0caf5"

  # Normal colors
  [colors.normal]
  black = "#414868"
  red = "#f7768e"
  green = "#9ece6a"
  yellow = "#e0af68"
  blue = "#7aa2f7"
  magenta = "#bb9af7"
  cyan = "#7dcfff"
  white = "#a9b1d6"

  # Bright colors
  [colors.bright]
  black = "#414868"
  red = "#f7768e"
  green = "#9ece6a"
  yellow = "#e0af68"
  blue = "#7aa2f7"
  magenta = "#bb9af7"
  cyan = "#7dcfff"
  white = "#c0caf5"

  [colors.selection]
  background = "#7c6f64"
  text = "#ffffff"



[window]
opacity = 0.9
# decorations = "none"
dimensions = { columns =90 , lines =25 }
padding = {x=3, y=0}
dynamic_padding = true

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 12.0
glyph_offset = {x=0, y=2}
offset= { x =0, y=3}

[cursor]    
style = { shape = "Beam", blinking = "Always" }
thickness = 0.20

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux new -s main"]
