-- local null_ls = require "null-ls"
--
-- local b = null_ls.builtins
--
-- local sources = {
--
--   -- webdev stuff
--   -- b.formatting.deno_fmt, -- choosed deno for ts/js files cuz its very fast!
--   -- b.formatting.prettier.with { filetypes = { "html", "markdown", "css" } }, -- so prettier works only on these filetypes
--   b.formatting.prettierd,
--
--   -- Lua
--   b.formatting.stylua,
--
--   -- go
--   b.formatting.gofumpt,
--   b.formatting.goimports_reviser,
--   b.formatting.golines,
--
--   -- sql
--   b.formatting.sql_formatter,
-- }
-- null_ls.setup {
--   debug = true,
--   sources = sources,
--
--   -- format on save https://github.com/jose-elias-alvarez/null-ls.nvim/wiki/Formatting-on-save
--   on_attach = function(client, bufnr)
--     local augroup = vim.api.nvim_create_augroup("LspFormatting", {})
--     if client.supports_method "textDocument/formatting" then
--       vim.api.nvim_clear_autocmds { group = augroup, buffer = bufnr }
--       vim.api.nvim_create_autocmd("BufWritePre", {
--         group = augroup,
--         buffer = bufnr,
--         callback = function()
--           vim.lsp.buf.format { bufnr = bufnr }
--         end,
--       })
--     end
--   end,
-- }
